### ISSUE TITLE
MAC Address

### ISSUE THREAD

**Issue by 0xtf** [melisska/ufiber_nano_serial_hack#1]
First of all, REALLY amazing work with the program! Works like a charm in the latest firmware. Thank you for your work.

I was wondering if an option to also change the MAC address could be added?

Thank you, and once again, amazing job!!

**Comment by v-a-c-u-u-m** [comment]
Thank you for your feedback. Added a function to change the MAC. I will wait when you test the function.

**Comment by 0xtf** [comment]
Wow! That’s awesome! I’ll report back here ASAP (I’m not home at the
moment).

Thank you!!

**Comment by 0xtf** [comment]
TESTED! Working perfectly! Thank you @melisska! One small suggestion: change the "usage" part of the script so that it aligns with the docs (or change the docs so that it aligns with the script usage helper). 

Once again, thank you very much!
