### ISSUE TITLE
Request for help New old firmware version and settings xml

### ISSUE THREAD

**Issue by MrX0r** [melisska/ufiber_nano_serial_hack#2]
Hello I have various problems with the adjustment, can you help me with my problem if you need more information I can give it to you.

I have a UFiber Loco FIRMWARE v2.0.1.

The following is written on my China ISP "ONU Modem".

PON: 112233445566 -- MAC 12 Digit
SN: 12345678901234  -- 14 Digit

The firmware v4.1.0.1 is available can I use this version? or better not?

About my problem
```
./ubi_serial_hack.py -r 192.168.1.1 -p 22 --serial 12:34:56:78:90:12:34 --mac 11:22:33:44:55:66

[+] Downloaded mtdblock3.BIN
[!] Hashsum of mtdblock3.BIN (sha256): d3bf8392a87ad78ce85a8474ee80bfcbd32e95018bfade9c696e8699dcf575ec
[~] nvram_version:    6
[~] boot_line:        "e=192.168.1.1:ffffff00 h=192.168.1.254 g= r=f f=vmlinux i=bcm963xx_fs_kernel d=1 p=0 c= a=                                                     "
[~] board_id:         "UBNT_SFU_6848   "
[~] main_thread:      0
[~] psi_size:         24
[~] num_mac_addr:     5
[~] base_mac_addr:    secret
[~] old_check_sum:    0xffffffff
[~] vendor_id:        "UBNT"
[~] serial_id:        secret
[~] serial_formatted:  secret
[~] gpon_password:    "           "
[~] checksum:         0x9a30eae
[-] Abnormal termination
[!] Your board_id is UBNT_SFU_6848   . You can use the --insecure flag at your own risk.
```

In my .xml I have other parameters that I think are important for the ONT (ISP).

```
GPON ONU MODEL" Value="XXX" 3 Digit
AUTH KEY Value="XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX" 32 Digit
PON VENDOR ID" Value="XXXX" 4 Digit
GPON SN Value="XXXXXXXXXXXX"12 Digit
GPON PLOAM PASSWORD Value="XXXXXXXXXX" 10 Digit
LOID is not used!
```

```
HW SERIAL NO Value="XXXXX112233445566 " 5 X Digit and then the MAC address

The "ISP ONT" uses IPoE DHCP no user name or password!
And vid Value "XXX" 3 digits
```

Can you help me with what exactly I should do?

Many thanks.

**Comment by TheM4rc0** [comment]
How do I set up a different vendor I need
gpon_sn_vendor_id = ABCD
gpon_sn_serial_id = BBBB00000000

**Comment by v-a-c-u-u-m** [comment]
Serial field has 8 bytes, try 4 bytes of ABCD + 4 bytes of numbers, then 4 bytes of BBBB + 4 of numbers, like this:

AAAA1234 -> 41:42:43:44:31:32:33:34
BBBB1234 -> 42:42:42:42:31:32:33:34

Some of them should work.
And if the script was not tested on your firmware, then add the --insecure flag at your own risk.

**Comment by TheM4rc0** [comment]
Hello @melisska 

Somehow this no longer works on the Loco

`/ubi_serial_hack.py --insecure -r 192.168.1.1 -p 22 --serial 41:42:43:44:31:32:33:34`
= SERIAL NUMBER ABCD31323334

ASCII Text to Hex Code Converter

I need serial
`RTKG11111111 = 52 54 4b 47 31 31 31 31 31 31 31 31`

But Vendor: `MONU = 4d 4f 4e 55`

How do I do this?

Many thanks.
