### ISSUE TITLE
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xf2 in position 0: invalid continuation byte

### ISSUE THREAD

**Issue by Jojonintendo** [melisska/ufiber_nano_serial_hack#3]
Hello,

I have installed firmware 2.1.1 on my UFiber Nano G in order to change its Serial and MAC, but I always get this error after the "serial_formatted" line:

> Traceback (most recent call last):
>   File "./ubi_serial_hack.py", line 341, in <module>
>     hack(args.host, args.port, args.username, args.serial, args.mac, args.nossh, args.insecure)
>   File "./ubi_serial_hack.py", line 263, in hack
>     board_id = nvram_info(mtdblock3)
>   File "./ubi_serial_hack.py", line 205, in nvram_info
>     log.info('gpon_password:    "{}"'.format(  gpon_password.decode()  ))

I have latest Python on Arch Linux and also the correct dependencies.

What can I try?

Thank you for your work!

**Comment by v-a-c-u-u-m** [comment]
# Try to add:
print(gpon_password) # before error line and show output for me

maybe you have a non-standard name or shifted bytes

**Comment by Jojonintendo** [comment]
This gives me the following additional line before the error:
`b'\xf2\x02\x00\x15)\x19t\x00\x00\x00\x00'`
This is weird because this is not exactly the password I have set through the GUI.

**Comment by v-a-c-u-u-m** [comment]
Try to comment with #
```python
#log.info('gpon_password: "{}"'.format( gpon_password.decode() ))
```
and show output, maybe some byte-filds have shifted or your provider have a strange password

**Comment by Jojonintendo** [comment]
Thanks for your reply, that was it. Now the output finishes correctly, reporting that the new firmware has been uploaded. After rebooting the Nano G, the new serial number is showing, so everything is fine now!

Thank you so much for your time and help on this.
