### ISSUE TITLE
Broken link

### ISSUE THREAD

**Issue by paride** [melisska/ufiber_nano_serial_hack#5]
The following link:

https://blog.onedefence.com/changing-the-gpon-serial-on-the-ubiquiti-ufiber-nano-g-part-two/

listed in the `README.md` file is unfortunately broken. The page is still available via archive.org and it's very informative:

https://web.archive.org/web/20190214022357/https://blog.onedefence.com/changing-the-gpon-serial-on-the-ubiquiti-ufiber-nano-g-part-two/

It could be worth pointing the archived copy.

**Comment by v-a-c-u-u-m** [comment]
Thank you! Fixed!
