### ISSUE TITLE
UF-Loco support

### ISSUE THREAD

**Issue by galvesribeiro** [melisska/ufiber_nano_serial_hack#9]
Hello!

Can you use your script agains a UF-Loco? Or does it only work with the Nano-G?

Thanks for all the work on this!

Best regards

**Comment by nighoa** [comment]
Hi community,

I can answer to your question. I'm having a uFiber Loco with the latest firmware 4.3.0 and I can confirm that everything works properly as expected.

You just need to use the "insecure" flag when you want to apply your modifications.

Best regards,

Nig

**Comment by v-a-c-u-u-m** [comment]
You need to download the mtdblock3 via ssh manually and after then upload it to some hosting because I do not have a LOCO firmware

**Comment by galvesribeiro** [comment]
Cool. I've built a tool after I've researched both devices according to the reference links you posted on README.md 

https://github.com/Unifi-Tools/UFiber.Configurator

I'm now researching how to adapt the tool for UF-Instant. If you have any ideas it would be very helpful.

Thank you!

**Comment by nighoa** [comment]
Hi,

I can give you that mtdblock3 for uFiber Loco. By the way, your tool @galvesribeiro seems pretty damn cool. 

Can it allow me to change the "HardwareVersion" value also ?

I will give it a try.

Thanks for the work.

Nig

**Comment by galvesribeiro** [comment]
Thanks! Probably. Just open an issue there for a feature request and we will see what it takes to get that.
